using Parrot.Config;
using Parrot.Context;
using Parrot.Events;
using Parrot.Llm;
using Parrot.Permissions;
using Parrot.Process;
using Parrot.Questions;
using Parrot.Skills;
using Parrot.Store;
using Parrot.Tools;
using Parrot.Web;

namespace Parrot.Agent;

internal sealed record AgentSessionScopeArguments(
    AgentIdentity Identity,
    AgentSessionParentLink ParentLink,
    ModelSelector Model,
    IModelRouter Router,
    IEventBroker EventBroker,
    IEventRepository EventRepository,
    ToolWorkspace Workspace,
    IImageArtifactRepository Images,
    WebFetcher WebFetcher,
    AgentTaskConfig AgentTasks,
    AgentSendConfig AgentSend,
    RequestLimitsConfig RequestLimits,
    ToolDefinitionCatalog ToolDefinitions,
    IReadOnlyList<string> ReadOnlyExecCommandPrefixes,
    ProcessRunner ProcessRunner,
    UserSessionResources Resources,
    ISystemPromptProvider SystemPromptProvider,
    AgentScratchDirectory Scratch,
    IAgentPathEnvironment PathEnvironment,
    Compactor Compactor,
    IPromptTemplateCatalog PromptTemplates,
    IMode Mode,
    AgentSessionSecurity Security,
    AgentSkills Skills,
    IPermissionBroker Permissions,
    IAgentRegistry Registry,
    IQuestionBroker UserQuestions,
    TimeProvider TimeProvider,
    Parrot.Diagnostics.IDiagnosticLog Diagnostics,
    CancellationToken Lifetime);
