using Parrot.AgentTasks;
using Parrot.Config;
using Parrot.Context;
using Parrot.Events;
using Parrot.Llm;
using Parrot.Permissions;
using Parrot.Process;
using Parrot.Questions;
using Parrot.Queues;
using Parrot.Skills;
using Parrot.Statuses;
using Parrot.Store;
using Parrot.Tools;
using Parrot.Web;

namespace Parrot.Agent;

internal sealed record AgentSessionScopeArguments(
    AgentIdentity Identity,
    AgentSessionParentLink ParentLink,
    ModelSelector Model,
    ModelRouter Router,
    EventBroker EventBroker,
    EventRepository EventRepository,
    ToolWorkspace Workspace,
    ImageArtifactRepository Images,
    WebFetcher WebFetcher,
    AgentTaskConfig AgentTasks,
    RequestLimitsConfig RequestLimits,
    AgentTaskRunCatalog AgentTaskRuns,
    ToolDefinitionCatalog ToolDefinitions,
    IReadOnlyList<string> ReadOnlyExecCommandPrefixes,
    ShellProcessOwners ShellProcesses,
    ISystemPromptProvider SystemPromptProvider,
    AgentScratchDirectory Scratch,
    AgentPathEnvironment PathEnvironment,
    Compactor Compactor,
    PromptTemplateCatalog PromptTemplates,
    IMode Mode,
    AgentSessionSecurity Security,
    AgentSkills Skills,
    PermissionBroker Permissions,
    RuntimeStatus Status,
    IAgentRegistry Registry,
    AgentQueues Queues,
    QuestionBroker UserQuestions,
    TimeProvider TimeProvider,
    Parrot.Diagnostics.IDiagnosticLog Diagnostics,
    CancellationToken Lifetime);
