using Parrot.Config;
using Parrot.Context;
using Parrot.Events;
using Parrot.Llm;
using Parrot.Permissions;
using Parrot.Process;
using Parrot.Questions;
using Parrot.Queues;
using Parrot.Statuses;
using Parrot.Store;
using Parrot.Tools;
using Parrot.Web;

namespace Parrot.Agent;

internal sealed record AgentSessionScopeArguments(
    IAgentSessionScope Scope,
    AgentIdentity Identity,
    AgentSessionParentScope ParentScope,
    ModelSelector Model,
    ModelRouter Router,
    EventBroker EventBroker,
    EventRepository EventRepository,
    ToolWorkspace Workspace,
    ImageArtifactRepository Images,
    WebFetcher WebFetcher,
    AgentTaskConfig AgentTasks,
    ToolDefinitionCatalog ToolDefinitions,
    IReadOnlyList<string> ReadOnlyExecCommandPrefixes,
    ShellProcessOwners ShellProcesses,
    ISystemPromptProvider SystemPromptProvider,
    AgentScratchDirectory Scratch,
    Compactor Compactor,
    PromptTemplateCatalog PromptTemplates,
    IMode Mode,
    AgentSessionSecurity Security,
    PermissionBroker Permissions,
    RuntimeStatus Status,
    AgentRegistry Registry,
    AgentQueues Queues,
    QuestionBroker UserQuestions,
    TimeProvider TimeProvider,
    CancellationToken Lifetime);
