<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Parrot.Core.Tests</RootNamespace>
    <IsTestProject>true</IsTestProject>
    <NoWarn>$(NoWarn);CA1859</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Parrot.Infrastructure/Parrot.Infrastructure.csproj" />
  </ItemGroup>

</Project>
