<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Parrot.Cli.Tests</RootNamespace>
    <IsTestProject>true</IsTestProject>
    <NoWarn>$(NoWarn);CA1859</NoWarn>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Parrot.StatusProviders/Parrot.StatusProviders.csproj" />
    <ProjectReference Include="../../src/Parrot.Tool.Queue/Parrot.Tool.Queue.csproj" />
    <ProjectReference Include="../../src/Parrot.Tool.Process/Parrot.Tool.Process.csproj" />
    <ProjectReference Include="../../src/Parrot.Composition/Parrot.Composition.csproj" />
    <ProjectReference Include="../../src/Parrot.Cli/Parrot.Cli.csproj" />
  </ItemGroup>

</Project>
