<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Parrot</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Parrot.Common/Parrot.Common.csproj" />
    <ProjectReference Include="../Parrot.Core/Parrot.Core.csproj" />
    <ProjectReference Include="../Parrot.Tools/Parrot.Tools.csproj" />
    <ProjectReference Include="../Parrot.Foundation/Parrot.Foundation.csproj" />
    <ProjectReference Include="../Parrot.Infrastructure/Parrot.Infrastructure.csproj" />
    <ProjectReference Include="../Parrot.Llm/Parrot.Llm.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Pure.DI" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="parrot" />
    <InternalsVisibleTo Include="Parrot.Core.Tests" />
    <InternalsVisibleTo Include="Parrot.Cli.Tests" />
  </ItemGroup>

</Project>
