<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Parrot</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Parrot.Common/Parrot.Common.csproj" />
    <ProjectReference Include="../Parrot.Tool.Queue/Parrot.Tool.Queue.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Scriban" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Parrot.Composition" />
    <InternalsVisibleTo Include="parrot" />
    <InternalsVisibleTo Include="Parrot.Core.Tests" />
    <InternalsVisibleTo Include="Parrot.Cli.Tests" />
    <InternalsVisibleTo Include="Parrot.Tools.Tests" />
  </ItemGroup>

</Project>
